# Generated by Django 5.0.2 on 2025-05-06 17:25

import job.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_job_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='img',
            field=models.ImageField(default='images/default.png', upload_to=job.models.upload_location),
        ),
    ]
